import click

categories = ["Electronics", "Clothing", "Books"]
products = {
    "Electronics": ["TV", "Laptop", "Phone"],
    "Clothing": ["Shirt", "Jeans", "Dress"],
    "Books": ["Novel", "Textbook", "Magazine"]
}
cart = []
bills = []


@click.group()
def mycart():
    """Welcome to MyCart - CLI E-commerce app.
    how to enter the input 
    python cli.project Mycart (#commands from the option)"""


@mycart.command()
def view_categories():
    """View the list of categories."""
    click.echo("Categories:")
    for category in categories:
        click.echo(f"- {category}")


@mycart.command()
@click.argument("category")
def view_products(category):
    """View all the products under a particular category."""
    if category in products:
        click.echo(f"Products under {category}:")
        for product in products[category]:
            click.echo(f"- {product}")
    else:
        click.echo("Category not found.")


@mycart.command()
@click.argument("product")
def view_product_details(product):
    """View product details."""
    # Fetch product details from the database or an external API
    click.echo(f"Details for product: {product}")


@mycart.command()
@click.argument("product")
def add_to_cart(product):
    """Add products to the cart."""
    cart.append(product)
    click.echo(f"{product} added to the cart.")


@mycart.command()
@click.argument("product")
def remove_from_cart(product):
    """Remove products from the cart."""
    if product in cart:
        cart.remove(product)
        click.echo(f"{product} removed from the cart.")
    else:
        click.echo(f"{product} is not in the cart.")


@mycart.command()
def view_cart():
    """View the contents of the cart."""
    if cart:
        click.echo("Cart contents:")
        for product in cart:
            click.echo(f"- {product}")
    else:
        click.echo("Your cart is empty.")


@mycart.command()
def buy():
    """Buy products from the cart and generate the bill."""
    if cart:
        total_amount = len(cart) * 1000  # Assuming each product costs Rs 1000
        discount = 500 if total_amount > 10000 else 0
        final_amount = total_amount - discount

        # Generate the bill and add it to the list of bills
        bill = {
            "cart": cart,
            "total_amount": total_amount,
            "discount": discount,
            "final_amount": final_amount
        }
        bills.append(bill)

        click.echo(f"Bill generated:\n"
                   f"Total amount: Rs {total_amount}\n"
                   f"Discount: Rs {discount}\n"
                   f"Final amount: Rs {final_amount}")
        cart.clear()
    else:
        click.echo("Your cart is empty. Nothing to buy.")


@click.group()
def admin():
    """Admin commands for MyCart.
    how to enter the input for admin
    python cli.project admin (#commands from the option)"""


@admin.command()
@click.argument("category")
def add_category(category):
    """Add categories."""
    categories.append(category)
    click.echo(f"{category} added to categories.")


@admin.command()
@click.argument("category")
@click.argument("product")
def add_product(category, product):
    """Add products to a category."""
    if category in products:
        products[category].append(product)
        click.echo(f"{product} added to {category}.")
    else:
        click.echo("Category not found.")


@admin.command()
def view_user_cart():
    """View details of products added to user carts."""
    if cart:
        click.echo("User carts:")
        for user_cart in cart:
            click.echo(f"- User: {user_cart['user']}, Cart: {user_cart['cart']}")
    else:
        click.echo("No products added to user carts.")


@admin.command()
def view_all_bills():
    """View all the bills generated by users."""
    if bills:
        click.echo("All bills:")
        for bill in bills:
            click.echo(f"- Cart: {bill['cart']}, Total amount: Rs {bill['total_amount']}, "
                       f"Discount: Rs {bill['discount']}, Final amount: Rs {bill['final_amount']}")
    else:
        click.echo("No bills generated.")


@click.group()
def cli():
    """MyCart - CLI E-commerce app.
     how to enter the input 
     python cli.project (#commands from the option)"""
    pass


cli.add_command(mycart)
cli.add_command(admin)

if __name__ == "__main__":
    cli()
